### ISSUE TITLE
Create card component persists on board change

### ISSUE THREAD

**Issue by DanNisenson** [DanNisenson/trello-client#38]
If CreateCard is rendered and board is changed -> component remains rendered.
Also needs a little styling but I can take care of that no problem.
@eduardpeters

**Comment by eduardpeters** [comment]
I figured the issue was opened for the CreateList component, not Create Card. Was able to reproduce the bug. Logic should be fixed on the linked Pull Request, plus a bit of styling, mainly as rendered height was not right (noticed this and fixed it on my DnD PR last night as well). No issue with any further styling you may want to add!
